// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIiyrgKT6_K88H5slmFu2rbqE-v4MLrQE',
    appId: '1:246198538073:web:1dfae73f45bbc830328648',
    messagingSenderId: '246198538073',
    projectId: 'monitor-9b5c6',
    authDomain: 'monitor-9b5c6.firebaseapp.com',
    databaseURL: 'https://monitor-9b5c6-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-9b5c6.appspot.com',
    measurementId: 'G-RY0JJSGS0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqHTJ3_q6rMXp7Vvl4UK88sdQYFbmPpBc',
    appId: '1:246198538073:android:4c88a50ad3cd4d42328648',
    messagingSenderId: '246198538073',
    projectId: 'monitor-9b5c6',
    databaseURL: 'https://monitor-9b5c6-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-9b5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0buU563_CwWzAzPdla8TX7s1u75Y3y0E',
    appId: '1:246198538073:ios:5e3748e7d7c0da53328648',
    messagingSenderId: '246198538073',
    projectId: 'monitor-9b5c6',
    databaseURL: 'https://monitor-9b5c6-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-9b5c6.appspot.com',
    iosBundleId: 'com.example.pipeinsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0buU563_CwWzAzPdla8TX7s1u75Y3y0E',
    appId: '1:246198538073:ios:5e3748e7d7c0da53328648',
    messagingSenderId: '246198538073',
    projectId: 'monitor-9b5c6',
    databaseURL: 'https://monitor-9b5c6-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-9b5c6.appspot.com',
    iosBundleId: 'com.example.pipeinsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIiyrgKT6_K88H5slmFu2rbqE-v4MLrQE',
    appId: '1:246198538073:web:b876cbc4d6d48d85328648',
    messagingSenderId: '246198538073',
    projectId: 'monitor-9b5c6',
    authDomain: 'monitor-9b5c6.firebaseapp.com',
    databaseURL: 'https://monitor-9b5c6-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-9b5c6.appspot.com',
    measurementId: 'G-T0P5G0917X',
  );

}